[development]
APP_ALLOWED_HOSTS=["*"] 
APP_DATABASES__default__ENGINE="" 
APP_DATABASES__default__NAME="" 
APP_DATABASES__default__USER=""
APP_DATABASES__default__HOST="postgres" 
APP_MEDIA_ROOT="" 
APP_MEDIA_URL="" 


[production]
APP_ALLOWED_HOSTS=["*"] 
APP_DATABASES__default__ENGINE="" 
APP_DATABASES__default__NAME="" 
APP_DATABASES__default__USER="" 
APP_DATABASES__default__HOST="postgres" 
APP_MEDIA_ROOT="" 
APP_MEDIA_URL=""

