version: '3.8'

volumes:
  app_pg_data:
    name: app_pg_data
  app_media_data:
    name: app_media_data
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - APP_ALLOWED_HOSTS=["*"] 
      - APP_DATABASES__default__ENGINE="django.db.backends.postgresql" 
      - APP_DATABASES__default__NAME="ecomm" 
      - APP_DATABASES__default__USER="admin"
      - APP_DATABASES__default__PASSWORD="admin" 
      - APP_DATABASES__default__HOST="postgres" 
      - APP_MEDIA_ROOT="/usr/src/app/media" 
      - APP_MEDIA_URL="/media/"
      - APP_DOMAIN=http://0.0.0.0:8000/           
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/usr/src/app
      - PATH="${PATH}:/home/python/.local/bin"
      - APP_REDIS_HOST="redis"
      - APP_REDIS_PORT=6379

  postgres:
    image: "postgres:12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecomm
    volumes:
      - "app_pg_data:/var/lib/postgresql/data"
  
  