version: '3.8'

volumes:
  app_pg_data:
    name: app_pg_data
  app_media_data:
    name: app_media_data
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - migration
      - postgres
    environment:
      - APP_ALLOWED_HOSTS=["*"] 
      - APP_DATABASES__default__ENGINE="django.db.backends.postgresql" 
      - APP_DATABASES__default__NAME="ecomm" 
      - APP_DATABASES__default__USER="admin"
      - APP_DATABASES__default__PASSWORD="admin" 
      - APP_DATABASES__default__HOST="postgres" 
      - APP_MEDIA_ROOT="/usr/src/app/media" 
      - APP_MEDIA_URL="/media/"
      - APP_DOMAIN=http://0.0.0.0:8000/           
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/usr/src/app
      - PATH="${PATH}:/home/python/.local/bin"
      - APP_REDIS_HOST="redis"
      - APP_REDIS_PORT=6379

  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres

  fixture:  
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - migration
      - postgres



  postgres:
    image: "postgres:12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecomm
    volumes:
      - "app_pg_data:/var/lib/postgresql/data"
  
  redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis
  worker:
    build: .
    command: rq worker --with-scheduler --url redis://redis:6379
    volumes:
      - ./:/usr/src/app/
      - ./media:/usr/src/app/media
    depends_on:
      - postgres
      - redis
    environment:
      - APP_ALLOWED_HOSTS=["*"] 
      - APP_DATABASES__default__ENGINE="django.db.backends.postgresql" 
      - APP_DATABASES__default__NAME="ecomm" 
      - APP_DATABASES__default__USER="admin"
      - APP_DATABASES__default__PASSWORD="admin" 
      - APP_DATABASES__default__HOST="postgres" 
      - APP_MEDIA_ROOT="/usr/src/app/media" 
      - APP_MEDIA_URL="/media/"
      - APP_DOMAIN=http://0.0.0.0:8000/           
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/usr/src/app
      - PATH="${PATH}:/home/python/.local/bin"
      - APP_REDIS_HOST="redis"
      - APP_REDIS_PORT=6379
  

  
