# Generated by Django 5.0 on 2023-12-09 08:56

import checkout.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('main_color', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('initial_stock', models.IntegerField(blank=True, null=True)),
                ('current_stock', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to=checkout.models.Product.product_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='checkout.productcategory')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
