# Generated by Django 5.0 on 2023-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_productattributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('purchased', 'Purchased'), ('expired', 'Expired')], max_length=30)),
                ('products', models.ManyToManyField(related_name='products_cart', to='checkout.product')),
            ],
        ),
    ]
